### ISSUE TITLE
Help please how to start this bot no errors :(

### ISSUE THREAD

**Issue by Taker54** [MD3XTER/Twitch-Farmer#13] opened 2019-02-13 03:00 UTC
Help please

**Comment by MD3XTER** [comment] 2019-02-13 09:36
Hi, I would like to help you, but I need more information on why it's not starting. Did you follow the installation process?

**Comment by Taker54** [comment] 2019-02-13 23:26
Can you show me how it works and its configurations? I just want to get spectators, I do not want followers. What should I do?
https://www.youtube.com/watch?v=fhzdzXJ25zk 
ERROR**^^
Thanks :)

**Comment by MD3XTER** [comment] 2019-02-13 23:36
you need to leave the first line in the csv file, as it used by the bot. Next, you fill it following this example: https://github.com/MD3XTER/Twitch-Farmer#usage

**Comment by Taker54** [comment] 2019-02-14 09:18
Py.exe: What channel should I follow? : taker33_rt
My configs,
Accounts.csv: arked777,Taker1111,taker33_rt,101.51.141.60:36459
Proxyes.csv: 
101.51.141.60:36459,
101.51.121.14:39130,
101.255.94.130:51372,
(Shocks4 live)

**Comment by MD3XTER** [comment] 2019-02-14 09:21
This is how your csv files should look like:

Accounts CSV
```csv
username,password,following_channel,used_proxy
andrei,123123,,
```
Proxies CSV
```csv
username,password,following_channel,used_proxy
proxy,status
123.123.132.123:1232,
```

**Comment by Taker54** [comment] 2019-02-14 09:51
You can make a video explaining that and putting it to work, if you want I give you the account. I'm clumsy I'm sorry

**Comment by Taker54** [comment] 2019-02-14 14:01
Can you give me one with data so I can understand it? Please

**Comment by MD3XTER** [comment] 2019-02-14 14:07
@Taker54 I just [wrote](https://github.com/MD3XTER/Twitch-Farmer/issues/13#issuecomment-463553809) you how my files look like.

Accounts CSV:
`I have a user with username: andrei and password: 123123`

Proxies CSV:
`I have a proxy with ip: 123.123.132.123:1232`

If you want to add more, just add more accounts and proxies following that format.

**Comment by MD3XTER** [comment] 2019-02-15 08:38
@Taker54 did you manage to fix your issue?

**Comment by Taker54** [comment] 2019-02-20 00:14
You can put a false account so you can understand it and a proxy. Thank you, im sorry

**Comment by MD3XTER** [comment] 2019-02-20 15:24
<img width="468" alt="screen shot 2019-02-20 at 4 23 55 pm" src="https://user-images.githubusercontent.com/7466068/53102437-ee562680-352b-11e9-98d9-d85987a2d9c0.png">

**Comment by Taker54** [comment] 2019-02-21 00:00
Hi andrew, im using shock 4, this is my error.
Google ChromeDriver:
This page does not work www.twitch.tv has not sent any data.
ERR_EMPTY_RESPONSE

py.exe
Using proxy: [185.212.126.92:52957]

DevTools listening on ws://127.0.0.1:59834/devtools/browser/813fc080-f3d7-4ac4-a747-dcd753488ff0
[arked666] Singing in...
--------------------------------
Time expired, changing proxy...
Using previous account: [arked666]

--------------------------------
No more proxies!!!
--------------------------------
Pres 'Enter' to Exit

**Comment by MD3XTER** [comment] 2019-02-21 00:10
The problem is in proxies, you have to buy some good ones, take a look at this [issue](https://github.com/MD3XTER/Twitch-Farmer/issues/11#issuecomment-437634270), he had some similar problems.

**Comment by Taker54** [comment] 2019-02-21 00:13
Im using proxy`s with 80 ping, proxy not good? Sorry for my english

**Comment by Taker54** [comment] 2019-02-21 00:14
Im testing proxy`s - http, https, shocks 4 and shocks 5, What type of proxy do you use? please

**Comment by MD3XTER** [comment] 2019-02-21 00:19
It should either of them, make sure the proxy is good. I have seen so many cases where the bot didn't work because of bad proxies. Check your proxies with this [tool](http://www.proxy-checker.org) and see if they are good.

**Comment by Taker54** [comment] 2019-02-21 00:21
Im rec video okey, wait please 👍

**Comment by Taker54** [comment] 2019-02-21 00:22
What kind of proxy should I use? shock5, shock4....

**Comment by MD3XTER** [comment] 2019-02-21 00:28
Use socks 4

**Comment by Taker54** [comment] 2019-02-21 00:47
This is my error
https://www.youtube.com/watch?v=MlOQ89nFQdY

**Comment by MD3XTER** [comment] 2019-02-21 00:56
ok, I will have a look myself tomorrow and come back with a solution

**Comment by Taker54** [comment] 2019-02-21 00:59
okey, thanks bro :100:

**Comment by Taker54** [comment] 2019-02-21 23:54
Hello, you have found a solution brother :(

**Comment by MD3XTER** [comment] 2019-02-22 13:48
@Taker54 I have just tested with good proxies and it's working. As I said, don't use free proxies, you will need to spend money on private ones. You can check that the bot is working with some free proxies: http://spys.one/en/

**Comment by MD3XTER** [comment] 2019-03-01 08:28
I am gonna assume that you have fixed your problem, so I will close this issue right now. Feel free to open a new issue if you have any other problems!

**Closed by MD3XTER** 2019-03-01 08:28 UTC
